"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

import os
import sys
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / ".env")

# Secret key setting from .env
SECRET_KEY = os.getenv("SECRET_KEY")

if not SECRET_KEY:
    from django.core.exceptions import ImproperlyConfigured

    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")

# Debug
DEBUG = os.getenv("DEBUG", "False") == "True"

# Get str of allowed hosts from .env and then convert to a list
ALLOWED_HOSTS_CSV = os.getenv("ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_CSV.split(",") if host.strip()]

# Get str of trusted origins from .env and then convert to a list
CSRF_TRUSTED_ORIGINS_CSV = os.getenv("CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in CSRF_TRUSTED_ORIGINS_CSV.split(",") if origin.strip()
]

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "cv",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if not DEBUG:
    # The whitenoise documentation recommends inserting it right after SecurityMiddleware.
    MIDDLEWARE.insert(
        MIDDLEWARE.index("django.middleware.security.SecurityMiddleware"),
        "whitenoise.middleware.WhiteNoiseMiddleware",
    )

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            # Enable template debug for coverage if explicitly requested, otherwise follow DEBUG setting
            "debug": os.getenv("TEMPLATE_DEBUG", "False") == "True" or DEBUG,
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
DATABASES = {}
if os.getenv("DATABASE_URL"):
    DATABASES["default"] = dj_database_url.config(
        conn_max_age=600,
        conn_health_checks=True,
    )
elif os.getenv("PGDATABASE"):
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ["PGDATABASE"],
        "USER": os.environ["PGUSER"],
        "PASSWORD": os.environ["PGPASSWORD"],
        "HOST": os.environ["PGHOST"],
        "PORT": os.environ["PGPORT"],
    }
else:
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",  # type: ignore[typeddict-item]
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Define where you will put your source static files (e.g., global css/js)
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Configure Whitenoise to compress and hash files
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}

# Login and Logout Redirect URLs
LOGIN_URL = "login"  # Points to the named URL pattern 'login'
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Logging Configuration
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} [{levelname}] {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": os.getenv("LOG_LEVEL", "WARNING"),
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": LOGS_DIR / "django.log",
            "formatter": "verbose",
            "when": "H",
            "interval": int(os.getenv("LOG_BACKUP_INTERVAL_HOURS", 1)),
            "backupCount": int(os.getenv("LOG_BACKUP_COUNT", 24 * 30)),
        },
    },
    "root": {
        "handlers": ["file"],
        "level": "WARNING",
    },
    "loggers": {
        "django": {
            "handlers": ["file"],
            "level": "INFO",
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["file"],
            "level": "DEBUG",  # Only logs SQL if DEBUG=True in settings
            "propagate": False,
        },
        "django.request": {
            "handlers": ["file"],
            "level": "WARNING",  # Logs 4xx as WARNING, 5xx as ERROR
            "propagate": False,
        },
        "django.security": {
            "handlers": ["file"],
            "level": "INFO",
            "propagate": False,
        },
        "config": {
            "handlers": ["file"],
            "level": "INFO",
            "propagate": False,
        },
        "cv": {
            "handlers": ["file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

ADMIN_URL = os.getenv("ADMIN_URL")

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Caching
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "my_cache_table",  # The name of the table in the database
    },
}

if DEBUG and "pytest" in "".join(sys.argv) and sys.modules.get("pytest") is not None:
    # Use a faster, insecure password hasher for tests to speed up user creation/login
    PASSWORD_HASHERS = [
        "django.contrib.auth.hashers.MD5PasswordHasher",
    ]

    # Use in-memory caching instead of the database cache during tests
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        },
    }

    # Prevent log file I/O during tests to further improve speed
    # This disables the 'file' handler defined in your LOGGING setting
    if "handlers" in LOGGING and "file" in LOGGING["handlers"]:  # type: ignore[operator]
        LOGGING["handlers"]["file"] = {"class": "logging.NullHandler"}  # type: ignore[index]
